

# Introduction to TensorFlow


In [1]:
import numpy as np


In [2]:
# Importing Tensorflow

import tensorflow as tf
print(tf.__version__)

2.7.0


In [ ]:
# Creating tensor with tf.constant()
Constant = tf.constant(7)
Constant

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
tf.constant([1, 2, 3, 4, 5, 6], dtype=float)

<tf.Tensor: shape=(6,), dtype=float32, numpy=array([1., 2., 3., 4., 5., 6.], dtype=float32)>

In [ ]:
a = np.array([[1, 2, 3], [4, 5,6]])
tf.constant(a)

<tf.Tensor: shape=(2, 3), dtype=int64, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

* Scalar is a single number
* Vector: a number with direction (ex wind speed and direction)
* Martix: a 2 dimensional array of elements
* Tensor: An n dimensional array of numbers (where n can be any number. if n=0, tensor is scalar, n=1, tensor is 1 dimensional vector)

In [ ]:
a.shape

(2, 3)

In [ ]:
# ndim is for number of dimensions in a tensor
a.ndim

2

##### Number of dimensions = Number of elements in a shape

In [ ]:
Constant.shape

TensorShape([])

In [ ]:
Constant.ndim

0

### Creating tensor with `tf.Variable`

In [ ]:
change_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([7,10])
change_tensor, unchangable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>)

In [ ]:
#let's try to change/assign the value to changable_tensor

change_tensor[0].assign(7)
change_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#let's try to change/assign the value to unchangable_tensor
unchangable_tensor[0].assign(10)

AttributeError: ignored

### Creating random Tensors

In [ ]:
#Creat a randon tensor

random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = [3,2])

random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape = [3,2])

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

In [ ]:
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape = [3,2])

random_2 = tf.random.Generator.from_seed(32)
random_2 = random_2.normal(shape = [3,2])

random_1, random_2, random_1 == random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[ 0.7901182 ,  1.585549  ],
        [ 0.4356279 ,  0.23645182],
        [-0.1589871 ,  1.302304  ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[False, False],
        [False, False],
        [False, False]])>)

## Understand About Shuffel in TensorFlow

In [ ]:
not_shuffel = tf.constant([[10,7],
                           [2,5],
                           [3,7],
                           [11,23],
                           [34,12]])
tf.random.shuffle(not_shuffel)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  7],
       [34, 12],
       [11, 23],
       [ 2,  5]], dtype=int32)>

In [ ]:
tf.random.shuffle(not_shuffel)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[ 3,  7],
       [11, 23],
       [ 2,  5],
       [34, 12],
       [10,  7]], dtype=int32)>

In [ ]:
tf.random.set_seed(32)
tf.random.shuffle(not_shuffel, seed = 21)

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[34, 12],
       [10,  7],
       [11, 23],
       [ 3,  7],
       [ 2,  5]], dtype=int32)>

In [ ]:
# Creating a tensor ones

tf.ones(shape = [3,4])

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Creating a tensor Zeros
tf.zeros(shape = [5,2])

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
a = np.arange(1, 25)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

#convert Numpy arrany to TensorFlow tensor

In [ ]:
Numpy_Tensor = tf.constant(a)
Numpy_Tensor

<tf.Tensor: shape=(24,), dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
Numpy_Tensor_shape1 = tf.constant(a, shape= [3,8])
Numpy_Tensor_shape1

<tf.Tensor: shape=(3, 8), dtype=int64, numpy=
array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24]])>

In [ ]:
Numpy_Tensor_shape2 = tf.Variable(a)
Numpy_Tensor_shape2

<tf.Variable 'Variable:0' shape=(24,) dtype=int64, numpy=
array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])>

In [ ]:
Numpy_Tensor_shape3 = tf.Variable(a, shape = [8,3])
Numpy_Tensor_shape3

ValueError: ignored

### Getting information from tensor

In [6]:
# creat rank /diminsion 4 tensor

rank_4_tensor = tf.zeros(shape= [3,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(3, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]

In [9]:
# Get various attributes of tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along axis 0 of tensor:", rank_4_tensor.shape[0])
print("Elements along last axis of tensor:", rank_4_tensor.shape[-1])
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor))
print("Total number of elements (2*3*4*5):", tf.size(rank_4_tensor).numpy()) # .numpy() converts to NumPy array


Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (3, 3, 4, 5)
Elements along axis 0 of tensor: 3
Elements along last axis of tensor: 5
Total number of elements (2*3*4*5): tf.Tensor(180, shape=(), dtype=int32)
Total number of elements (2*3*4*5): 180


### Indexing with tensors

In [16]:
rank_4_tensor[0,0,:,:]

<tf.Tensor: shape=(4, 5), dtype=float32, numpy=
array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]], dtype=float32)>

In [19]:
A = np.arange(0,40)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [26]:
rank_tensor = tf.constant(A, shape= [2,2,2,5])
rank_tensor

<tf.Tensor: shape=(2, 2, 2, 5), dtype=int64, numpy=
array([[[[ 0,  1,  2,  3,  4],
         [ 5,  6,  7,  8,  9]],

        [[10, 11, 12, 13, 14],
         [15, 16, 17, 18, 19]]],


       [[[20, 21, 22, 23, 24],
         [25, 26, 27, 28, 29]],

        [[30, 31, 32, 33, 34],
         [35, 36, 37, 38, 39]]]])>

In [29]:
rank_tensor[:,:,:,1:3]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=int64, numpy=
array([[[[ 1,  2],
         [ 6,  7]],

        [[11, 12],
         [16, 17]]],


       [[[21, 22],
         [26, 27]],

        [[31, 32],
         [36, 37]]]])>

## Tensor Manuplations (Basic Operations)

`+`, `-`, `*`, and `/`

In [34]:
tensor = tf.constant([[[2,5],
                      [4,6]],
                     [[1,2],
                      [3,7]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[2, 5],
        [4, 6]],

       [[1, 2],
        [3, 7]]], dtype=int32)>

In [35]:
tensor +5

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[ 7, 10],
        [ 9, 11]],

       [[ 6,  7],
        [ 8, 12]]], dtype=int32)>

## Tensor (Matrix) miltiple with scalar.

In [36]:
tensor * 10

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[20, 50],
        [40, 60]],

       [[10, 20],
        [30, 70]]], dtype=int32)>

In [37]:
tf.math.multiply(tensor,10)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[20, 50],
        [40, 60]],

       [[10, 20],
        [30, 70]]], dtype=int32)>

In [38]:
tf.multiply(tensor,10)

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[20, 50],
        [40, 60]],

       [[10, 20],
        [30, 70]]], dtype=int32)>

** NOTE ** : `tf.math.multiply(tensor,10)` == `tf.multiply(tensor,10)` == `tensor * 10`

> for faster computation better to use tensor builtin functions.


###### Multplication of two matrices.

MAtrix multplication is most commpon operatiopn in Machine Learning.

In [40]:
tensor1 = tf.constant([[1,2],
                       [3,5]])
tensor1 * tensor1 # Element wise multiplication

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 1,  4],
       [ 9, 25]], dtype=int32)>

In [41]:
tf.matmul(tensor1, tensor1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 7, 12],
       [18, 31]], dtype=int32)>

### Tensor transformations

In [60]:
X = tf.constant([[1,2,3,4],
                      [1,2,3,6],
                      [2,3,4,5]])
Y = tf.constant([[1,2,1],
                 [3,4,2],
                 [5,6,3]])
X, Y


(<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
 array([[1, 2, 3, 4],
        [1, 2, 3, 6],
        [2, 3, 4, 5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 1],
        [3, 4, 2],
        [5, 6, 3]], dtype=int32)>)

In [45]:
X @ Y # Matrix multiplication in python

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[46, 56],
       [58, 70],
       [61, 75]], dtype=int32)>

In [46]:
tf.matmul(X,Y)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[46, 56],
       [58, 70],
       [61, 75]], dtype=int32)>

In [48]:
tf.transpose(X)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[1, 1, 2],
       [2, 2, 3],
       [3, 3, 4],
       [4, 6, 5]], dtype=int32)>

In [50]:
tf.reshape(Y, shape=(8,1))

<tf.Tensor: shape=(8, 1), dtype=int32, numpy=
array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [6],
       [7]], dtype=int32)>

In [53]:
tf.reshape(X, shape = (6,2))

<tf.Tensor: shape=(6, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4],
       [1, 2],
       [3, 6],
       [2, 3],
       [4, 5]], dtype=int32)>

## `tf.transordot()` 

In [61]:
X.shape, Y.shape

(TensorShape([3, 4]), TensorShape([3, 3]))

In [63]:
tf.tensordot(tf.transpose(X), Y, axes =1)

<tf.Tensor: shape=(4, 3), dtype=int32, numpy=
array([[14, 18,  9],
       [23, 30, 15],
       [32, 42, 21],
       [47, 62, 31]], dtype=int32)>

## Changing datatype of tensor

In [65]:
X.dtype, Y.dtype

(tf.int32, tf.int32)

In [67]:
C = tf.cast(X,tf.int16)
C, C.dtype

(<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
 array([[1, 2, 3, 4],
        [1, 2, 3, 6],
        [2, 3, 4, 5]], dtype=int16)>, tf.int16)

In [68]:
E = tf.cast(Y, tf.float16)
E, E.dtype

(<tf.Tensor: shape=(3, 3), dtype=float16, numpy=
 array([[1., 2., 1.],
        [3., 4., 2.],
        [5., 6., 3.]], dtype=float16)>, tf.float16)

## Finding positional Max and Min

In [11]:
tf.random.set_seed(23)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.43993807, 0.09729016, 0.8235066 , 0.22273934, 0.3318541 ,
       0.25352108, 0.34313524, 0.45672834, 0.60538435, 0.46301937,
       0.50474167, 0.5150137 , 0.5610179 , 0.13842285, 0.9624418 ,
       0.5469624 , 0.98602736, 0.7543844 , 0.19885683, 0.991691  ,
       0.47549224, 0.17814577, 0.89089394, 0.24397457, 0.85176086,
       0.8440089 , 0.7800995 , 0.07725966, 0.2982911 , 0.57528853,
       0.2866801 , 0.6147386 , 0.64163256, 0.90662575, 0.01245236,
       0.4213121 , 0.91082525, 0.27526963, 0.68104875, 0.50922835,
       0.20153081, 0.29233146, 0.43840623, 0.9122982 , 0.87145627,
       0.47187352, 0.20997441, 0.5697775 , 0.59673095, 0.42037487],
      dtype=float32)>

In [16]:
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=19>

In [14]:
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.991691>

In [17]:
tf.math.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.991691>

In [18]:
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=34>

In [19]:
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.012452364>

## Squeezing the tensor

In [22]:
tf.random.set_seed(23)
G = tf.constant(tf.random.uniform(shape = [1,1,1,1,1,50]))
G

<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.43993807, 0.09729016, 0.8235066 , 0.22273934,
            0.3318541 , 0.25352108, 0.34313524, 0.45672834,
            0.60538435, 0.46301937, 0.50474167, 0.5150137 ,
            0.5610179 , 0.13842285, 0.9624418 , 0.5469624 ,
            0.98602736, 0.7543844 , 0.19885683, 0.991691  ,
            0.47549224, 0.17814577, 0.89089394, 0.24397457,
            0.85176086, 0.8440089 , 0.7800995 , 0.07725966,
            0.2982911 , 0.57528853, 0.2866801 , 0.6147386 ,
            0.64163256, 0.90662575, 0.01245236, 0.4213121 ,
            0.91082525, 0.27526963, 0.68104875, 0.50922835,
            0.20153081, 0.29233146, 0.43840623, 0.9122982 ,
            0.87145627, 0.47187352, 0.20997441, 0.5697775 ,
            0.59673095, 0.42037487]]]]]], dtype=float32)>

Squeezing the tensor means, it get rid of the all single dimensions in the 1 dimensions in the tensor.

In [23]:
G_squeezes = tf.squeeze(G)
G_squeezes, G_squeezes.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.43993807, 0.09729016, 0.8235066 , 0.22273934, 0.3318541 ,
        0.25352108, 0.34313524, 0.45672834, 0.60538435, 0.46301937,
        0.50474167, 0.5150137 , 0.5610179 , 0.13842285, 0.9624418 ,
        0.5469624 , 0.98602736, 0.7543844 , 0.19885683, 0.991691  ,
        0.47549224, 0.17814577, 0.89089394, 0.24397457, 0.85176086,
        0.8440089 , 0.7800995 , 0.07725966, 0.2982911 , 0.57528853,
        0.2866801 , 0.6147386 , 0.64163256, 0.90662575, 0.01245236,
        0.4213121 , 0.91082525, 0.27526963, 0.68104875, 0.50922835,
        0.20153081, 0.29233146, 0.43840623, 0.9122982 , 0.87145627,
        0.47187352, 0.20997441, 0.5697775 , 0.59673095, 0.42037487],
       dtype=float32)>, TensorShape([50]))

## Onehot encoding in TernsorFlow

In [25]:
#Some_list = ['Red', 'Green', 'Blue']
Some_list = [0,1,2]
tf.one_hot(Some_list, depth = 3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>